name: 2026 Mood

on:
  schedule:
    - cron: '0 05 * * *'  # daily


  workflow_dispatch:      # Manual trigger

jobs:
  run-daily:
    runs-on: ubuntu-latest

    env:
      client_id_youtube: ${{ secrets.YTA_CLIENT_ID }}
      client_secret_youtube: ${{ secrets.YTA_CLIENT_SECRET }}
      YOUTUBE_REFRESH_TOKEN: ${{ secrets.YT_MOOD_RT }}



    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          persist-credentials: true  # Allow committing back

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run script
        uses: nick-fields/retry@v3
        with:
          timeout_minutes: 10
          max_attempts: 3
          command: python 2026mood.py
          retry_on: error


